ARG BUN_VERSION=1.2.5
FROM oven/bun:${BUN_VERSION}-slim AS base

WORKDIR /app

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

FROM install AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ENV NODE_ENV=production

RUN mkdir -p .pylon
RUN bun run pylon build

FROM base AS release
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /app/.pylon .pylon
COPY --from=prerelease /app/package.json .

USER bun
EXPOSE 3005/tcp
ENTRYPOINT [ "bun", "run", "/app/.pylon/index.js" ]