services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    image: rento-web
    container_name: rento-web
    env_file: ./apps/web/docker.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api-gateway

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    image: rento-admin
    container_name: rento-admin
    env_file: ./apps/admin/docker.env
    ports:
      - "5173:80"
    networks:
      - app-network
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    image: rento-api-gateway
    container_name: rento-api-gateway
    ports:
      - "3001:3001"
    env_file: ./apps/api-gateway/docker.env
    depends_on:
      - property-service
    networks:
      - app-network

  property-service:
    build:
      context: ./services/property
      dockerfile: Dockerfile
    image: rento-property-service
    container_name: rento-property-service
    env_file: ./services/property/docker.env
    ports:
      - "3005:3005"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
