services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    image: rento-web
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api-gateway

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    image: rento-admin
    ports:
      - "5173:80"
    networks:
      - app-network
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
    image: rento-api-gateway
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
