export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  MISSING_USER_ID = "MISSING_USER_ID",
  MISSING_NOTIFICATION_MESSAGE = "MISSING_NOTIFICATION_MESSAGE",
  MISSING_NOTIFICATION_TYPE = "MISSING_NOTIFICATION_TYPE",
  MISSING_NOTIFICATION_TITLE = "MISSING_NOTIFICATION_TITLE",
  MISSING_NOTIFICATION_USER_ID = "MISSING_NOTIFICATION_USER_ID",
  MISSING_NOTIFICATION_SEND_AT = "MISSING_NOTIFICATION_SEND_AT",
  MISSING_NOTIFICATION_STATUS = "MISSING_NOTIFICATION_STATUS",
  MISSING_NOTIFICATION_TYPE_EMAIL = "MISSING_NOTIFICATION_TYPE_EMAIL",
  MISSING_NOTIFICATION_TYPE_IN_APP = "MISSING_NOTIFICATION_TYPE_IN_APP",
  MISSING_NOTIFICATION_ID = "MISSING_NOTIFICATION_ID",

  SEND_EMAIL_FAILED = "SEND_EMAIL_FAILED",
  MISSING_USER_SERVICE_API_URL = "MISSING_USER_SERVICE_API_URL",
  MISSING_USER_SERVICE_API_URL_PATH = "MISSING_USER_SERVICE_API_URL_PATH",
  NOT_FOUND_EMAIL_FROM_USER_ID = "NOT_FOUND_EMAIL_FROM_USER_ID",
}
