export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  MISSING_USER_ID = "MISSING_USER_ID",

  MISSING_TENANT_ID = "MISSING_TENANT_ID",
  MISSING_HOST_ID = "MISSING_HOST_ID",
  MISSING_PROPERTY_ID = "MISSING_PROPERTY_ID",
  MISSING_CONVERSATION_ID = "MISSING_CONVERSATION_ID",
  MISSING_MESSAGE_ID = "MISSING_MESSAGE_ID",

  INVALID_PROPERTY_ID = "INVALID_PROPERTY_ID",
  INVALID_CONVERSATION_ID = "INVALID_CONVERSATION_ID",

  CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND",
}
