server:
  port: 8082

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: ${ELASTIC_URI}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    connection-timeout: 5000
    socket-timeout: 5000
    ssl:
      verification-mode: none
    restclient:
      sniffer:
        interval: 60000
        delay-after-failure: 30000

  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        endpoints: ${ELASTIC_URI}
        username: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
        ssl:
          verification-mode: none

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true

# Cấu hình scheduler đồng bộ dữ liệu
sync:
  elasticsearch:
    enabled: true
    cron: "0 0/5 * * * ?"  # Run every 5 minutes
    batch-size: 100

# Cấu hình logging
logging:
  level:
    root: INFO
    com.property.search: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: INFO