server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://ep-silent-fire-a1gvyuvl-pooler.ap-southeast-1.aws.neon.tech/rento-property?sslmode=require
    username: rento-property_owner
    password: npg_Sn1LWwU4lCQA
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: https://67912903224c4a45bc255ec063468186.ap-southeast-1.aws.found.io:443
    username: minhnguyet
    password: Learning-purpose-0
    connection-timeout: 5000
    socket-timeout: 5000
    ssl:
      verification-mode: none
    restclient:
      sniffer:
        interval: 60000
        delay-after-failure: 30000

  data:
    elasticsearch:
      repositories:
        enabled: true
      client:
        endpoints: https://67912903224c4a45bc255ec063468186.ap-southeast-1.aws.found.io:443
        username: minhnguyet
        password: Learning-purpose-0
        ssl:
          verification-mode: none

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Cấu hình scheduler đồng bộ dữ liệu
sync:
  elasticsearch:
    enabled: true
    cron: "0 0/5 * * * ?"  # Run every 5 minutes
    batch-size: 100

# Cấu hình logging
logging:
  level:
    root: INFO
    com.property.search: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: INFO