export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  AMENITY_ALREADY_EXISTS = "AMENITY_ALREADY_EXISTS",
  CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  RULE_ALREADY_EXISTS = "RULE_ALREADY_EXISTS",

  MISSING_TITLE = "MISSING_TITLE",
  MISSING_DESCRIPTION = "MISSING_DESCRIPTION",
  MISSING_ADDRESS = "MISSING_ADDRESS",
  MISSING_LATITUDE = "MISSING_LATITUDE",
  MISSING_LONGITUDE = "MISSING_LONGITUDE",
  MISSING_PRICE_PER_NIGHT = "MISSING_PRICE_PER_NIGHT",
  MISSING_NUMBER_OF_GUESTS = "MISSING_NUMBER_OF_GUESTS",
  MISSING_NUMBER_OF_BEDROOMS = "MISSING_NUMBER_OF_BEDROOMS",
  MISSING_NUMBER_OF_BEDS = "MISSING_NUMBER_OF_BEDS",
  MISSING_NUMBER_OF_BATHROOMS = "MISSING_NUMBER_OF_BATHROOMS",
  MISSING_CATEGORY_ID = "MISSING_CATEGORY_ID",
  MISSING_AMENITY_ID = "MISSING_AMENITY_ID",
  MISSING_RULE_ID = "MISSING_RULE_ID",
  MISSING_IMAGE = "MISSING_IMAGE",

  INVALID_LATITUDE = "INVALID_LATITUDE",
  INVALID_LONGITUDE = "INVALID_LONGITUDE",
  INVALID_PRICE_PER_NIGHT = "INVALID_PRICE_PER_NIGHT",
  INVALID_NUMBER_OF_GUESTS = "INVALID_NUMBER_OF_GUESTS",
  INVALID_NUMBER_OF_BEDROOMS = "INVALID_NUMBER_OF_BEDROOMS",
  INVALID_NUMBER_OF_BEDS = "INVALID_NUMBER_OF_BEDS",
  INVALID_NUMBER_OF_BATHROOMS = "INVALID_NUMBER_OF_BATHROOMS",
  INVALID_CATEGORY_ID = "INVALID_CATEGORY_ID",
  INVALID_AMENITY_ID = "INVALID_AMENITY_ID",
  INVALID_RULE_ID = "INVALID_RULE_ID",
  INVALID_IMAGE = "INVALID_IMAGE",

  VALIDATION_FAILED = "VALIDATION_FAILED", // Fallback error code for validation errors
}
