server:
  port: 8080

spring:
  data:
    elasticsearch:
      client:
        endpoints: localhost:9200
        username: elastic
        password: changeme
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/property_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# Cấu hình scheduler đồng bộ dữ liệu
sync:
  elasticsearch:
    enabled: true
    cron: "0 */5 * * * ?" # Chạy mỗi 5 phút
    batch-size: 100 # Số lượng bản ghi đồng bộ mỗi lần

# Cấu hình logging
logging:
  level:
    root: INFO
    com.property: DEBUG
    org.springframework.data.elasticsearch: DEBUG 